/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        /* Design Token → Tailwind映射 (经验教训L6转化) */
        bg: 'var(--bg-surface)',
        surface: 'var(--bg-surface-elevated)',
        'surface-2': 'var(--bg-surface-hover)',
        'surface-3': 'var(--tw-surface-3)',
        'surface-deep': 'var(--bg-surface-deep)',
        border: 'var(--border-default)',
        'border-2': 'var(--border-subtle)',
        primary: 'var(--bg-primary)',
        'primary-2': 'var(--bg-primary-hover)',
        'primary-foreground': 'var(--bg-primary-foreground)',
        accent: 'var(--tw-accent)',
        'brand-accent': 'var(--brand-accent)',
        'brand-accent-hover': 'var(--brand-accent-hover)',
        danger: 'var(--status-danger)',
        'danger-bright': 'var(--status-danger-bright)',
        warn: 'var(--status-warning)',
        success: 'var(--status-success)',
        info: 'var(--status-info)',
        it: 'var(--tw-it)',
        manuf: 'var(--tw-manuf)',
        edu: 'var(--tw-edu)',
        finance: 'var(--tw-finance)',
        text: 'var(--text-primary)',
        'text-2': 'var(--text-secondary)',
        'text-3': 'var(--text-tertiary)',
        'text-muted': 'var(--text-muted)',
        /* Brand palette */
        brand: {
          50: 'var(--brand-50)',
          100: 'var(--brand-100)',
          200: 'var(--brand-200)',
          300: 'var(--brand-300)',
          400: 'var(--brand-400)',
          500: 'var(--brand-500)',
          600: 'var(--brand-600)',
          700: 'var(--brand-700)',
          800: 'var(--brand-800)',
          900: 'var(--brand-900)',
        },
      },
      spacing: {
        '1': 'var(--space-1)',
        '2': 'var(--space-2)',
        '3': 'var(--space-3)',
        '4': 'var(--space-4)',
        '6': 'var(--space-6)',
        '8': 'var(--space-8)',
      },
      fontSize: {
        xs: 'var(--font-xs)',
        sm: 'var(--font-sm)',
        base: 'var(--font-base)',
        lg: 'var(--font-lg)',
        xl: 'var(--font-xl)',
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
      },
      transitionDuration: {
        fast: '150ms',
        normal: '200ms',
        slow: '300ms',
      },
      fontFamily: {
        sans: ['-apple-system', 'SF Pro Display', 'PingFang SC', 'Microsoft YaHei', 'sans-serif'],
      },
      animation: {
        'pulse-glow': 'pulseGlow 2.5s ease-in-out infinite',
      },
      keyframes: {
        pulseGlow: {
          '0%, 100%': { opacity: '1', boxShadow: '0 0 8px color-mix(in srgb, var(--tw-accent) 30%, transparent)' },
          '50%': { opacity: '0.5', boxShadow: '0 0 2px color-mix(in srgb, var(--tw-accent) 10%, transparent)' },
        },
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};
